name: Deploy to Nexus

on:
  workflow_dispatch:  # Permite execução manual via interface do GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Maven settings.xml
        run: |
          #!/bin/bash
          sudo mkdir -p ~/.m2
          echo > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>wsl_nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF
          ls ~/./m2
          cat ~/.m2/settings.xml

      - name: Build and deploy with Maven
        run: mvn clean deploy -DskipTests
